version: '3.8'

services:
  # Test database
  postgres-test:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: patriot_heavy_ops_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d patriot_heavy_ops_test"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Test Redis for caching
  redis-test:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_test_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Test application
  app-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      NODE_ENV: test
      DATABASE_URL: postgresql://test_user:test_password@postgres-test:5432/patriot_heavy_ops_test
      REDIS_URL: redis://redis-test:6379
      NEXTAUTH_SECRET: test-secret-key
      NEXTAUTH_URL: http://localhost:3000
    ports:
      - "3001:3000"
    depends_on:
      postgres-test:
        condition: service_healthy
      redis-test:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run test:integration

volumes:
  postgres_test_data:
  redis_test_data:
