name: Ana

on:
  # Monitor CI Test workflow completion
  workflow_run:
    workflows: ["CI Tests", "Optimized CI Tests"]
    types: [completed]
  # Monitor Cursor Bugbot completion (when it posts comments)
  issue_comment:
    types: [created]
  # Monitor Cursor Bugbot reviews (Issue #280 Fix)
  pull_request_review:
    types: [submitted]

permissions:
  actions: read
  contents: read
  issues: write
  pull-requests: write

jobs:
  # Analyze CI Test failures and add to Cursor TODO list
  analyze-ci-failures:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'failure'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Setup environment
        run: |
          echo "CURSOR_CLI=CURSOR_CLI" >> .env.local
          echo "GITHUB_ACCESS_TOKEN=${{ secrets.ORG_PAT }}" >> .env.local
          echo "NODE_ENV=production" >> .env.local
          echo "TOD_WEBHOOK_ENDPOINT=${{ secrets.TOD_WEBHOOK_ENDPOINT || 'http://localhost:3001/webhook/ana-failures' }}" >> .env.local
          echo "ANA_WEBHOOK_SECRET=${{ secrets.ANA_WEBHOOK_SECRET || 'dev-secret-key' }}" >> .env.local
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.ORG_PAT }}
          TOD_WEBHOOK_ENDPOINT: ${{ secrets.TOD_WEBHOOK_ENDPOINT }}
          ANA_WEBHOOK_SECRET: ${{ secrets.ANA_WEBHOOK_SECRET }}

      - name: Find associated PR
        id: find-pr
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ORG_PAT }}
          script: |
            // Find associated PR for this workflow run
            const { data: prs } = await github.rest.pulls.list({
              ...context.repo,
              state: 'open',
              head: `${context.repo.owner}:${{ github.event.workflow_run.head_branch }}`
            });

            if (prs.length === 0) {
              console.log("No open PR found for branch ${{ github.event.workflow_run.head_branch }}, skipping");
              return { pr_number: null };
            }

            const prNumber = prs[0].number;
            console.log(`Found PR #${prNumber} for failed CI Test workflow`);
            return { pr_number: prNumber.toString() };

      - name: Analyze CI Test failures and send to Tod webhook
        if: steps.find-pr.outputs.pr_number != 'null'
        run: |
          echo "🔍 Ana analyzing CI Test failures..."
          echo "Workflow: ${{ github.event.workflow_run.name }}"
          echo "Run ID: ${{ github.event.workflow_run.id }}"
          echo "PR: ${{ steps.find-pr.outputs.pr_number }}"
          echo "Webhook Endpoint: ${{ secrets.TOD_WEBHOOK_ENDPOINT || 'http://localhost:3001/webhook/ana-failures' }}"

          # Set up GitHub CLI authentication
          echo "${{ secrets.ORG_PAT }}" | gh auth login --with-token

          # Analyze workflow logs and send to Tod via webhook (Issue #282)
          if ! npx tsx scripts/ana-cli.ts analyze-ci-failures ${{ github.event.workflow_run.id }} ${{ steps.find-pr.outputs.pr_number }}; then
            echo "❌ Ana analysis failed, but continuing workflow"
            echo '{"todos": [], "summary": "Ana analysis failed", "analysisDate": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'"}' > ana-results.json
          fi

      - name: Upload analysis results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ana-ci-analysis-${{ github.event.workflow_run.id }}
          path: ana-results.json
          retention-days: 7

  # Analyze Cursor Bugbot reviews and add to Cursor TODO list
  analyze-cursor-bugbot:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, 'Cursor Bugbot')) ||
      (github.event_name == 'pull_request_review' && 
       github.event.review.user.login == 'cursor' &&
       github.event.review.state == 'COMMENTED')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Setup environment
        run: |
          echo "CURSOR_CLI=CURSOR_CLI" >> .env.local
          echo "GITHUB_ACCESS_TOKEN=${{ secrets.ORG_PAT }}" >> .env.local
          echo "NODE_ENV=production" >> .env.local
          echo "TOD_WEBHOOK_ENDPOINT=${{ secrets.TOD_WEBHOOK_ENDPOINT || 'http://localhost:3001/webhook/ana-failures' }}" >> .env.local
          echo "ANA_WEBHOOK_SECRET=${{ secrets.ANA_WEBHOOK_SECRET || 'dev-secret-key' }}" >> .env.local
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.ORG_PAT }}
          TOD_WEBHOOK_ENDPOINT: ${{ secrets.TOD_WEBHOOK_ENDPOINT }}
          ANA_WEBHOOK_SECRET: ${{ secrets.ANA_WEBHOOK_SECRET }}

      - name: Validate Cursor Bugbot event
        id: validate-event
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ORG_PAT }}
          script: |
            if (context.eventName === 'pull_request_review') {
              // Handle pull_request_review event (Issue #280 Fix)
              const review = context.payload.review;
              const prNumber = context.payload.pull_request.number;
              
              console.log(`Found Cursor Bugbot review on PR #${prNumber}, Review ID: ${review.id}`);
              return { 
                is_valid: true, 
                pr_number: prNumber.toString(),
                review_id: review.id.toString(),
                event_type: 'review'
              };
            } else if (context.eventName === 'issue_comment') {
              // Handle legacy issue_comment event (backward compatibility)
              if (!context.payload.issue.pull_request) {
                console.log("Comment is not on a PR, skipping");
                return { is_valid: false };
              }

              const prNumber = context.payload.issue.number;
              const commentId = context.payload.comment.id;
              
              console.log(`Found Cursor Bugbot comment on PR #${prNumber}, Comment ID: ${commentId}`);
              return { 
                is_valid: true, 
                pr_number: prNumber.toString(),
                comment_id: commentId.toString(),
                event_type: 'comment'
              };
            } else {
              console.log("Unknown event type, skipping");
              return { is_valid: false };
            }

      - name: Analyze Cursor Bugbot review and send to Tod webhook
        if: steps.validate-event.outputs.is_valid == 'true'
        run: |
          echo "🔍 Ana analyzing Cursor Bugbot..."
          echo "PR: ${{ steps.validate-event.outputs.pr_number }}"
          echo "Event Type: ${{ steps.validate-event.outputs.event_type }}"
          echo "Webhook Endpoint: ${{ secrets.TOD_WEBHOOK_ENDPOINT || 'http://localhost:3001/webhook/ana-failures' }}"

          # Set up GitHub CLI authentication
          echo "${{ secrets.ORG_PAT }}" | gh auth login --with-token

          # Choose analysis method based on event type (Issue #280 Fix)
          if [ "${{ steps.validate-event.outputs.event_type }}" = "review" ]; then
            echo "Review ID: ${{ steps.validate-event.outputs.review_id }}"
            # Use new pull_request_review method (Issue #280)
            if ! npx tsx scripts/ana-cli.ts analyze-cursor-bugbot-review ${{ steps.validate-event.outputs.pr_number }} ${{ steps.validate-event.outputs.review_id }}; then
              echo "❌ Ana Bugbot review analysis failed, but continuing workflow"
              echo '{"todos": [], "summary": "Ana Bugbot review analysis failed", "analysisDate": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'"}' > ana-results.json
            fi
          else
            echo "Comment ID: ${{ steps.validate-event.outputs.comment_id }}"
            # Use legacy issue_comment method (backward compatibility)
            if ! npx tsx scripts/ana-cli.ts analyze-cursor-bugbot ${{ steps.validate-event.outputs.pr_number }} ${{ steps.validate-event.outputs.comment_id }}; then
              echo "❌ Ana Bugbot comment analysis failed, but continuing workflow"
              echo '{"todos": [], "summary": "Ana Bugbot comment analysis failed", "analysisDate": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'"}' > ana-results.json
            fi
          fi

      - name: Upload analysis results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ana-cursor-analysis-${{ steps.validate-event.outputs.pr_number }}-${{ steps.validate-event.outputs.event_type }}
          path: ana-results.json
          retention-days: 7

      - name: Comment on PR with webhook integration status
        if: steps.validate-event.outputs.is_valid == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ORG_PAT }}
          script: |
            const fs = require('fs');
            let comment = '## 🤖 Ana Analysis Summary\n\n';

            try {
              if (fs.existsSync('ana-results.json')) {
                const results = JSON.parse(fs.readFileSync('ana-results.json', 'utf8'));
                
                if (results.todos && results.todos.length > 0) {
                  comment += `Found **${results.todos.length}** issues from Cursor Bugbot review:\n\n`;
                  results.todos.forEach((todo, index) => {
                    const priority = todo.priority === 'critical' ? '🔴' : 
                                   todo.priority === 'high' ? '🟠' : 
                                   todo.priority === 'medium' ? '🟡' : '🟢';
                    comment += `${index + 1}. ${priority} **${todo.priority.toUpperCase()}**: ${todo.content}\n`;
                    if (todo.files && todo.files.length > 0) {
                      comment += `   📁 **Files**: ${todo.files.join(', ')}\n`;
                    }
                    comment += '\n';
                  });
                  
                  comment += '---\n';
                  comment += '🤖 *Ana has sent these items to Tod webhook for Cursor TODO integration (Issue #282). Check Cursor for the full list.*';
                } else {
                  comment += '✅ No new issues detected from Cursor Bugbot review.';
                }
              } else {
                comment += 'ℹ️ No analysis results found.';
              }
            } catch (error) {
              comment += `❌ Error processing analysis: ${error.message}`;
            }

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
