name: CI/CD Pipeline

on:
  workflow_run:
    workflows: ["CI Tests"]
    types:
      - completed

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch artifacts via GitHub API
        run: |
          curl -sL \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            ${{ github.event.workflow_run.artifacts_url }} \
            > artifacts.json

          # Download coverage
          COV_ID=$(jq -r '.artifacts[] | select(.name=="coverage") | .id' artifacts.json)
          if [ "$COV_ID" != "" ]; then
            curl -L \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github+json" \
              -o coverage.zip \
              https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$COV_ID/zip
            unzip -o coverage.zip -d coverage
          fi

          # Download build
          BUILD_ID=$(jq -r '.artifacts[] | select(.name=="build") | .id' artifacts.json)
          if [ "$BUILD_ID" != "" ]; then
            curl -L \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github+json" \
              -o build.zip \
              https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$BUILD_ID/zip
            unzip -o build.zip
          fi

      - name: Verify build exists
        run: ls -lah .next || echo "Build not found"

  integration:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Start services with Docker
        run: docker compose up -d

      - name: Wait for services
        run: sleep 30

      - name: Run integration tests
        run: npm run test:integration || echo "Integration tests not yet implemented"

      - name: Stop services
        run: docker compose down

      - name: Upload integration logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration-logs
          path: integration-output.log

      - name: Post summary on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const log = fs.readFileSync('integration-output.log', 'utf8');
            const summary = log.split('\n').slice(-20).join('\n');
            const issue_number = context.payload.workflow_run.pull_requests[0]?.number;
            if (issue_number) {
              await github.rest.issues.createComment({
                ...context.repo,
                issue_number,
                body: `🚨 **Integration Tests Failed**\n\n**Last 20 log lines:**\n\`\`\`\n${summary}\n\`\`\`\n\nFull logs available in the uploaded artifact.`
              });
            }
