name: CI/CD Pipeline

on:
  workflow_run:
    workflows: ["CI Tests"]
    types:
      - completed

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download coverage
        uses: actions/download-artifact@v4
        with:
          name: coverage

      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: build

      - name: Extract build
        run: tar -xzf build.tar.gz

      - name: Verify build exists
        run: ls -lah .next || echo "Build not found"

  integration:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Start services with Docker
        run: docker compose up -d

      - name: Wait for services
        run: sleep 30

      - name: Run integration tests
        run: |
          set -o pipefail
          npm run test:integration 2>&1 | tee integration-output.log || exit 1

      - name: Stop services
        run: docker compose down

      # Always upload integration logs
      - name: Upload integration logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: integration-logs
          path: integration-output.log

      # Post summary to PR if integration tests failed
      - name: Post summary on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const log = fs.readFileSync('integration-output.log', 'utf8');
            const summary = log.split('\n').slice(-20).join('\n'); // last 20 lines
            const issue_number = context.payload.workflow_run.pull_requests[0]?.number;
            if (issue_number) {
              await github.rest.issues.createComment({
                ...context.repo,
                issue_number,
                body: `🚨 **Integration Tests Failed**\n\n**Last 20 log lines:**\n\`\`\`\n${summary}\n\`\`\`\n\nFull logs available in the uploaded artifact.`
              });
            }
