name: PR Comment Resolution Check

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, review_requested, review_request_removed]

jobs:
  check-comments:
    runs-on: ubuntu-latest

    steps:
      - name: Check for unresolved review comments
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const { data: reviews } = await github.rest.pulls.listReviewComments({
              ...context.repo,
              pull_number: prNumber,
              per_page: 100
            });

            // GitHub marks comments as "in_reply_to_id" when resolved; keep only root unresolved
            const unresolved = reviews.filter(r => r.in_reply_to_id === null);

            if (unresolved.length > 0) {
              core.setFailed(`❌ ${unresolved.length} unresolved comments remain.`);
            } else {
              core.info("✅ All review comments resolved.");
            }
