name: Vercel Logs to GitHub

on:
  check_suite:
    types: [completed]

jobs:
  fetch-vercel-logs:
    if: github.event.check_suite.app.name == 'Vercel'
    runs-on: ubuntu-latest

    steps:
      - name: Fetch latest deployment
        run: |
          curl -s -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
          "https://api.vercel.com/v13/deployments?projectId=<YOUR_PROJECT_ID>&limit=1" \
          > vercel.json
          cat vercel.json | jq .

      - name: Extract summary
        id: parse
        run: |
          STATE=$(jq -r '.deployments[0].readyState' vercel.json)
          URL=$(jq -r '.deployments[0].url' vercel.json)
          ERROR=$(jq -r '.deployments[0].error.message // "No error message available"' vercel.json)

          echo "state=$STATE" >> $GITHUB_OUTPUT
          echo "url=https://$URL" >> $GITHUB_OUTPUT
          echo "error=$ERROR" >> $GITHUB_OUTPUT

      - name: Comment on PR with logs
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.check_suite.pull_requests[0].number }}
          body: |
            🚨 **Vercel Deployment Failed**
            - **State:** ${{ steps.parse.outputs.state }}
            - **URL:** [Preview Deployment](${{ steps.parse.outputs.url }})
            - **Error:**  
              ```
              ${{ steps.parse.outputs.error }}
              ```
